Repository oithxs/hira-chan, pull requests merged in 2022-07, with the labels that each got.

#133 GitHub Actionsで不要なデータベースの作成をしないように
  .github/workflows/laravel.yml
Labels: Type: Refactoring

#137 ファイルのパスを修正
  docs/dev/Docker.md
Labels: Type: documentation, Close: Normal

#139 週間アクセスランキング追加
  app/Http/Livewire/Dashboard/Various.php
  composer.json
  composer.lock
  resources/views/dashboard/various.blade.php
Labels: Type: Feature, Priority: High

#140 スレッドの検索（カテゴリでの絞り込み検索可）
  app/Http/Livewire/Dashboard/Rankings.php
  app/Http/Livewire/Dashboard/Threads.php
  public/js/app_jquery.js
  resources/js/dashboard/Search_thread.js
  resources/views/dashboard/threads.blade.php
Labels: Type: Feature, Priority: High

#145 スレッド名に特殊文字を使用していてもアクセス可能に修正
  resources/views/dashboard/threads.blade.php
Labels: Type: bug

#146 いいねを押している場合に画像が表示されないのを修正
  public/css/app.css
  public/js/app_jquery.js
  resources/js/dashboard/Get_allRow.js
Labels: Type: Refactoring, Type: fix

#134 laravelのアップグレード
  .github/workflows/laravel.yml
  composer.json
  composer.lock
Labels: Type: Refactoring

#147 書き込みに返信を行いやすいように
  app/Http/Controllers/jQuery_ajax.php
  public/css/app.css
  public/js/app_jquery.js
  resources/js/dashboard/Get_allRow.js
  resources/js/dashboard/Reply_message.js
  resources/js/dashboard/Send_Row.js
  resources/views/dashboard/send-comment.blade.php
Labels: Type: Feature, Priority: High

#148 スレッドのソートができるように修正・未使用の箇所を削除
  app/Http/Livewire/Dashboard/Threads.php
  resources/views/dashboard/threads.blade.php
Labels: Type: Refactoring, Type: fix

#149 ドキュメントルートを変更せずに環境構築可能に
  .env.example
  config/livewire.php
  public/js/app_jquery.js
  resources/js/dashboard/Get_allRow.js
  resources/views/MyPage.blade.php
  resources/views/dashboard/header.blade.php
  resources/views/dashboard/messages.blade.php
  resources/views/dashboard/select-thread-pages.blade.php
  resources/views/dashboard/send-comment.blade.php
  resources/views/dashboard/threads.blade.php
  resources/views/hub.blade.php
  resources/views/keiziban.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/guest.blade.php
  resources/views/welcome.blade.php
Labels: Priority: Medium, Type: Refactoring

#150 現状のdocker環境構築では必要だったのでurlからpublicを消す手段追加
  .htaccess
  public/css/app.css
  public/js/app_jquery.js
  resources/js/dashboard/Get_allRow.js
Labels: Type: Refactoring

#151 Dockerの修正
  docs/dev/Docker.md
  docs/dev/docker-sample/.env.docker
  docs/dev/docker-sample/docker-compose.yml
  docs/dev/docker-sample/docker/php/Dockerfile
  docs/dev/docker-sample/docker/php/php.ini
Labels: Type: documentation, Status: Pending

#152 npmパッケージの更新
  package-lock.json
  package.json
Labels: Type: Refactoring

#153 npm packageの更新
  package-lock.json
Labels: Type: Refactoring
