Repository oithxs/hira-chan, pull requests merged in 2022-10, with the labels that each got.

#189 Feature/form design
  public/css/app.css
  public/js/app.js
  resources/css/default/welcome/normalize.css
  resources/css/default/welcome/welcome.css
  resources/views/dashboard/header.blade.php
  resources/views/dashboard/messages.blade.php
  resources/views/dashboard/rankings.blade.php
  resources/views/dashboard/send-comment.blade.php
  resources/views/dashboard/show.blade.php
  resources/views/dashboard/threads.blade.php
  resources/views/dashboard/various.blade.php
  resources/views/layouts/app.blade.php
  webpack.mix.js
Labels: Status: Pending, Type: design

#196 "hub" テーブルのリレーション・その活用
  README.md
  app/Http/Controllers/Dashboard/HubController.php
  app/Http/Controllers/Dashboard/NotLoggedIn/ThreadsController.php
  app/Http/Controllers/Dashboard/ThreadsController.php
  app/Http/Livewire/Dashboard/Messages.php
  app/Http/Livewire/Dashboard/Threads.php
  app/Http/Middleware/AccessLog.php
  app/Models/Hub.php
  app/Models/ThreadCategory.php
  app/Models/User.php
  database/migrations/2022_09_18_193501_add_column_thread_category_id_to_hub_table.php
  database/migrations/2022_09_18_193813_add_column_user_id_to_hub_table.php
  database/migrations/2022_09_18_194045_drop_column_thread_id_to_hub_table.php
  database/migrations/2022_09_18_194634_drop_column_thread_category_to_hub_table.php
  database/migrations/2022_09_18_194645_drop_column_thread_category_type_to_hub_table.php
  database/migrations/2022_09_18_194654_drop_column_user_email_to_hub_table.php
  database/migrations/2022_09_18_195651_rename_thread_name_to_name_on_hub_table.php
  public/css/app.css
  public/js/app.js
  resources/css/default/welcome/normalize.css
  resources/css/default/welcome/welcome.css
  resources/views/dashboard/header.blade.php
  resources/views/dashboard/messages.blade.php
  resources/views/dashboard/rankings.blade.php
  resources/views/dashboard/send-comment.blade.php
  resources/views/dashboard/show.blade.php
  resources/views/dashboard/threads.blade.php
  resources/views/dashboard/various.blade.php
  resources/views/layouts/app.blade.php
  webpack.mix.js
Labels: Type: Refactoring, Type: fix

#198 "likes" テーブルのリレーション・その活用
  app/Http/Controllers/Dashboard/LikeController.php
  app/Http/Controllers/Dashboard/NotLoggedIn/ClubThreadController.php
  app/Http/Controllers/Dashboard/NotLoggedIn/CollegeYearThreadController.php
  app/Http/Controllers/Dashboard/NotLoggedIn/DepartmentThreadController.php
  app/Http/Controllers/Dashboard/NotLoggedIn/JobHuntingThreadController.php
  app/Http/Controllers/Dashboard/NotLoggedIn/LectureThreadController.php
  app/Http/Controllers/Dashboard/NotLoggedIn/ThreadsController.php
  app/Http/Controllers/Dashboard/ThreadImagePathController.php
  app/Http/Controllers/Dashboard/ThreadsController.php
  app/Models/ClubThread.php
  app/Models/CollegeYearThread.php
  app/Models/DepartmentThread.php
  app/Models/JobHuntingThread.php
  app/Models/LectureThread.php
  app/Models/Like.php
  app/Models/ThreadImagePath.php
  app/Models/User.php
  database/migrations/2022_10_13_214551_add_column_club_thread_id_to_likes_table.php
  database/migrations/2022_10_13_214605_add_column_college_year_thread_id_to_likes_table.php
  database/migrations/2022_10_13_214616_add_column_department_thread_id_to_likes_table.php
  database/migrations/2022_10_13_214636_add_column_job_hunting_thread_id_to_likes_table.php
  database/migrations/2022_10_13_214646_add_column_lecture_thread_id_to_likes_table.php
  database/migrations/2022_10_14_214953_add_column_user_id_to_likes_table.php
  database/migrations/2022_10_14_215322_drop_column_thread_id_to_likes_table.php
  database/migrations/2022_10_14_215416_drop_column_message_id_to_likes_table.php
  database/migrations/2022_10_14_215433_drop_column_user_email_to_likes_table.php
  database/migrations/2022_10_15_151605_add_column_club_thread_id_to_thread_image_paths_table.php
  database/migrations/2022_10_15_151621_add_column_college_year_thread_id_to_thread_image_paths_table.php
  database/migrations/2022_10_15_151640_add_column_department_thread_id_to_thread_image_paths_table.php
  database/migrations/2022_10_15_151714_add_column_job_hunting_thread_id_to_thread_image_paths_table.php
  database/migrations/2022_10_15_151738_add_column_lecture_thread_id_to_thread_image_paths_table.php
  database/migrations/2022_10_15_153505_add_column_user_id_to_thread_image_paths_table.php
  database/migrations/2022_10_15_154007_drop_column_thread_id_to_thread_image_paths_table.php
  database/migrations/2022_10_15_154030_drop_column_message_id_to_thread_image_paths_table.php
  database/migrations/2022_10_15_154055_drop_column_user_email_to_thread_image_paths_table.php
  public/js/app_jquery.js
  resources/js/dashboard/Get_allRow.js
Labels: Type: Refactoring

#199 環境構築でVSCode devcontainerを使用する
  .devcontainer/devcontainer.json
  .devcontainer/postCreateCommand.sh
  .devcontainer/postStartCommand.sh
  .env.example
  .vscode/extensions.json
  .vscode/settings.json
  bin/setup-docker.sh
  bin/start-docker.sh
  bin/stop-docker.sh
  docker/.env.docker
  docker/app/Dockerfile
  docker/app/php/php.ini
  docker/app/postfix/main.cf
  docker/docker-compose.yml
  docker/mysql/Dockerfile
  docker/nginx/Dockerfile
  docker/nginx/default.conf
  docker/php/Dockerfile
  docker/phpmyadmin/Dockerfile
  docker/postfix/Dockerfile
  docs/README.md
  docs/Setup/VSCode_devcontainer.md
  docs/dev/Ubuntu-2204-Server.md
  docs/dev/Windows11.md
  docs/dev/auto_Ubuntu-2204-Server.md
  docs/dev/src/auto_Ubuntu-2204-Server.sh
  package-lock.json
Labels: Type: documentation, Type: Feature, Priority: Low

#200 postCreateCommand.shが正常に動作する様に修正
  .devcontainer/postCreateCommand.sh
Labels: Priority: Critical, Type: fix

#197 Feature/form design
  public/css/design.css
  public/js/app.js
  public/mix-manifest.json
  resources/css/default/dashboard/ranking.css
  resources/views/dashboard/rankings.blade.php
Labels: Status: Fix Needed, Type: design

#203 テーブルのリレーション設定に伴う不具合の修正
  app/Http/Livewire/Dashboard/SelectThreadPages.php
  app/Http/Livewire/Dashboard/Threads.php
  app/Models/AccessLog.php
  app/Models/AdminMenu.php
  app/Models/AdminPermission.php
  app/Models/ClubThread.php
  app/Models/CollegeYearThread.php
  app/Models/ContactAdministrator.php
  app/Models/DepartmentThread.php
  app/Models/Hub.php
  app/Models/JobHuntingThread.php
  app/Models/LectureThread.php
  app/Models/Like.php
  app/Models/SerializeDate.php
  app/Models/ThreadCategory.php
  app/Models/ThreadImagePath.php
  app/Models/User.php
  app/Models/UserPageTheme.php
  docker/docker-compose.yml
  docker/nginx/default.conf
  resources/views/dashboard/header.blade.php
  storage/app/public/.gitignore
Labels: Type: fix
