Repository oithxs/hira-chan, pull requests merged in 2022-06, with the labels that each got.

#83 環境構築手順の更新
  auto_setup.sh
  docs/auto_setup.md
  docs/setup.md
Labels: Type: documentation

#84 管理者用機能の一斉メールで改行出来る様に
  app/Mail/ContactMail.php
  app/Models/AdminMenu.php
  database/seeders/AdminInstallSeeder.php
  database/seeders/DatabaseSeeder.php
  docs/auto_setup.md
  docs/setup.md
  resources/views/emails/contact.blade.php
Labels: Type: documentation, Type: Feature, Type: admin

#91 アクセスランキングをダッシュボードに表示
  app/Http/Controllers/DashboardController.php
  app/Models/Get.php
  public/uploads/.gitignore
  resources/lang/ja.json
  resources/views/dashboard.blade.php
  resources/views/hub.blade.php
  resources/views/keiziban.blade.php
  resources/views/navigation-menu.blade.php
  routes/web.php
Labels: Type: bug, Type: documentation

#92 環境構築ドキュメントの更新
  auto_setup.sh
  docs/auto_setup.md
  docs/setup.md
Labels: Type: documentation

#93 Widnwos11での開発環境構築
  app/Admin/Controllers/UserController.php
  docs/README.md
  docs/dev/Ubuntu-2204-Server.md
  docs/dev/Windows11.md
  docs/dev/auto_Ubuntu-2204-Server.md
  docs/dev/src/auto_Ubuntu-2204-Server.sh
Labels: Type: documentation

#94 ドキュメントのファイルリンクを修正
  docs/README.md
Labels: Type: documentation

#96 管理者ユーザのみ特別な操作をできる様に
  app/Admin/Controllers/UserController.php
  app/Admin/Forms/MailForm.php
  app/Http/Controllers/jQuery_ajax.php
  app/Models/AdminActions.php
  app/Models/create_thread.php
  database/migrations/2014_10_12_000000_create_users_table.php
  public/css/app.css
  public/js/app_jquery.js
  resources/js/Delete_message.js
  resources/js/Delete_thread.js
  resources/js/Edit_thread.js
  resources/js/Get_allRow.js
  resources/js/Restore_message.js
  resources/lang/ja.json
  resources/views/dashboard.blade.php
  resources/views/emails/contact.blade.php
  resources/views/hub.blade.php
  resources/views/keiziban.blade.php
  resources/views/navigation-menu.blade.php
  resources/views/welcome.blade.php
  routes/web.php
  webpack.mix.js
Labels: Type: bug, Type: Feature, Type: admin

#100 コード整形
  .github/workflows/laravel.yml
  app/Admin/Controllers/PostController.php
  app/Admin/Controllers/UserController.php
  app/Admin/Extensions/Tools/GeneralUser.php
  app/Admin/Forms/MailForm.php
  app/Http/Controllers/AccountDelete.php
  app/Http/Controllers/DashboardController.php
  app/Http/Controllers/MyPage.php
  app/Http/Controllers/jQuery_ajax.php
  app/Http/Controllers/keizibanCTL.php
  app/Http/Controllers/showTablesCTL.php
  app/Mail/ContactMail.php
  app/Models/AdminActions.php
  app/Models/Get.php
  app/Models/Like.php
  app/Models/Record_AccessLog.php
  app/Models/Send.php
  app/Models/User.php
  app/Models/create_thread.php
  app/Notifications/VerifyEmailAddURL.php
  public/css/app.css
  public/css/design.css
  public/js/app.js
  public/mix-manifest.json
  resources/css/app.css
  resources/css/normalize.css
  resources/css/welcome.css
  resources/js/Create_thread.js
  resources/js/Delete_message.js
  resources/js/Delete_thread.js
  resources/js/Edit_thread.js
  resources/js/Get_allRow.js
  resources/js/Restore_message.js
  resources/js/Send_Row.js
  resources/views/MyPage.blade.php
  resources/views/dashboard.blade.php
  resources/views/emails/contact.blade.php
  resources/views/hub.blade.php
  resources/views/navigation-menu.blade.php
  resources/views/welcome.blade.php
  webpack.mix.js
Labels: Type: Refactoring

#102 不具合修正・コード改良・セキュリティ強化
  app/Admin/Controllers/UserController.php
  app/Http/Kernel.php
  app/Http/Middleware/IsAdmin.php
  app/Http/Middleware/PostAccess_only.php
  public/js/app_jquery.js
  resources/js/Delete_message.js
  resources/js/Delete_thread.js
  resources/js/Edit_thread.js
  resources/js/Restore_message.js
  routes/web.php
Labels: Type: Refactoring, Type: enhancement

#111 htmlのidを編集
  public/js/app_jquery.js
  resources/js/hub/Create_thread.js
  resources/js/hub/Delete_thread.js
  resources/js/hub/Edit_thread.js
  resources/js/keiziban/Delete_message.js
  resources/js/keiziban/Get_allRow.js
  resources/js/keiziban/Restore_message.js
  resources/js/keiziban/Send_Row.js
  resources/js/mypage/SelectPageThema.js
  resources/views/MyPage.blade.php
  resources/views/hub.blade.php
  resources/views/keiziban.blade.php
  webpack.mix.js
Labels: Close: Normal

#118 ログインと登録フォームのデザインを変更（#112）＋それに伴いそれらの処理を修正
  .env.example
  app/Actions/Fortify/CreateNewUser.php
  app/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php
  app/laravel/fortify/src/Http/Requests/LoginRequest.php
  composer.json
  config/AddConfig.php
  phpunit.xml
  resources/lang/ja.json
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  tests/Feature/_laravel/ApiTokenPermissionsTest.php
  tests/Feature/_laravel/AuthenticationTest.php
  tests/Feature/_laravel/BrowserSessionsTest.php
  tests/Feature/_laravel/CreateApiTokenTest.php
  tests/Feature/_laravel/DeleteAccountTest.php
  tests/Feature/_laravel/DeleteApiTokenTest.php
  tests/Feature/_laravel/EmailVerificationTest.php
  tests/Feature/_laravel/PasswordConfirmationTest.php
  tests/Feature/_laravel/PasswordResetTest.php
  tests/Feature/_laravel/ProfileInformationTest.php
  tests/Feature/_laravel/RegistrationTest.php
  tests/Feature/_laravel/TwoFactorAuthenticationSettingsTest.php
  tests/Feature/_laravel/UpdatePasswordTest.php
  tests/View/mypage/MyPageViewTest.php
Labels: Type: enhancement

#112 ログインと登録フォームのデザインを変更
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
Labels: help wanted

#119 一般ユーザの掲示板ハブやスレッドをトップページに移動
  app/Http/Controllers/DashboardController.php
  app/Http/Middleware/IsAdmin.php
  package-lock.json
  package.json
  phpunit.xml
  public/css/design.css
  public/js/app.js
  public/js/app_jquery.js
  public/mix-manifest.json
  resources/css/welcome/normalize.css
  resources/css/welcome/welcome.css
  resources/js/dashboard/Create_thread.js
  resources/js/dashboard/Get_allRow.js
  resources/js/dashboard/Send_Row.js
  resources/views/dashboard.blade.php
  resources/views/navigation-menu.blade.php
  resources/views/welcome.blade.php
  routes/web.php
  tests/Feature/hub/AuthenticationTest.php
  tests/Feature/hub/DeleteThreadTest.php
  tests/Feature/hub/EditThreadTest.php
  tests/Feature/keiziban/AuthenticationTest.php
  tests/Feature/keiziban/DeleteMessageTest.php
  tests/Feature/keiziban/RestoreMessageTest.php
  tests/Feature/mypage/AuthenticationTest.php
  tests/View/welcome/WelcomeViewTest.php
  webpack.mix.js
Labels: Type: enhancement

#120 掲示板ハブ表示のソート
  app/Http/Controllers/DashboardController.php
  app/Http/Controllers/showTablesCTL.php
  app/Models/Get.php
  resources/lang/ja.json
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  resources/views/dashboard.blade.php
  resources/views/hub.blade.php
  resources/views/keiziban.blade.php
  routes/web.php
Labels: Type: Feature

#125 ダッシュボードのモジュール分割
  app/Http/Controllers/DashboardController.php
  app/Http/Controllers/dashboard/DashboardController.php
  app/Http/Livewire/Dashboard/Header.php
  app/Http/Livewire/Dashboard/MainDisplay.php
  app/Http/Livewire/Dashboard/Messages.php
  app/Http/Livewire/Dashboard/Rankings.php
  app/Http/Livewire/Dashboard/SelectThreadPages.php
  app/Http/Livewire/Dashboard/SendComment.php
  app/Http/Livewire/Dashboard/Threads.php
  app/Http/Livewire/Dashboard/Various.php
  app/Models/Get.php
  bootstrap/cache/.gitignore
  public/js/app_jquery.js
  public/mix-manifest.json
  resources/js/dashboard/Get_allRow.js
  resources/views/dashboard.blade.php
  resources/views/dashboard/header.blade.php
  resources/views/dashboard/messages.blade.php
  resources/views/dashboard/rankings.blade.php
  resources/views/dashboard/select-thread-pages.blade.php
  resources/views/dashboard/send-comment.blade.php
  resources/views/dashboard/show.blade.php
  resources/views/dashboard/threads.blade.php
  resources/views/dashboard/various.blade.php
  resources/views/layouts/app.blade.php
  routes/web.php
  tests/Feature/dashboard/AuthenticationTest.php
Labels: Type: Feature, Type: Refactoring

#123 Feature/changetheme
  public/css/app.css
  public/css/design-dark.css
  public/css/design.css
  public/js/app.js
  public/mix-manifest.json
  resources/css/dark/dashboard/dark.css
  resources/css/dark/dashboard/nomal.css
  resources/css/welcome/normalize.css
  resources/css/welcome/welcome.css
  resources/views/layouts/app.blade.php
  webpack.mix.js
Labels: Type: Progress
