Repository oithxs/hira-chan, pull requests merged in 2023-04, with the labels that each got.

#270 書き込み時のコントローラでバリデーションが行われるように変更
  app/Http/Controllers/API/PostController.php
  app/Http/Controllers/Dashboard/ThreadsController.php
  app/Http/Requests/Posts/StoreRequest.php
  app/Rules/MaxLineRule.php
  app/Rules/TrimRule.php
  public/css/app.css
  public/js/app_jquery.js
  resources/js/dashboard/Send_Row.js
  tests/Unit/app/Http/Controllers/Dashboard/ThreadsController/StoreTest.php
Labels: Type: enhancement

#272 バリデーションエラーの形式が同じになるように，Posts/StoreRequest の例外処理関数を削除
  app/Exceptions/Handler.php
  app/Http/Requests/Posts/StoreRequest.php
Labels: Type: enhancement

#273 スレッド作成を行うAPIの作成
  app/Http/Controllers/API/HubController.php
  app/Http/Requests/Threads/StoreRequest.php
  app/Services/Tables/HubService.php
  routes/api.php
Labels: Type: Feature

#271 コンフリクトを起こしやすい npm run dev などでビルドされるファイルを削除・gitの管理から除外
  public/.gitignore
  public/css/app.css
  public/css/design-dark.css
  public/css/design-error.css
  public/css/design.css
  public/js/app.js
  public/js/app.js.LICENSE.txt
  public/js/app_jquery.js
Labels: Type: chore

#274 screenコマンドを使用して，laravelのキュー・webpackのwatch をセッションで常に実行するように変更
  .devcontainer/postStartCommand.sh
  docker/app/Dockerfile
Labels: Type: chore

#275 コンテキストを利用してLaravelからReactへ渡す値を追加する
  resources/ts/src/components/Header/Header.tsx
  resources/ts/src/features/auth/components/Logout.tsx
  resources/ts/src/features/threads/api/hubIndex.ts
  resources/ts/src/features/threads/api/threadPrimaryCategoryIndex.ts
  resources/ts/src/features/threads/api/threadSecondaryCategoryIndex.ts
  resources/ts/src/features/threads/components/Layout.tsx
  resources/ts/src/hooks/useContext.ts
  resources/ts/src/providers/app.tsx
  resources/ts/src/types/index.ts
  resources/views/layouts/layout.blade.php
  routes/api.php
Labels: Type: Refactoring, Type: enhancement

#276 Hotfix/v1.0.0 beta.2
  resources/views/welcome.blade.php
Labels: Type: fix

#277 fix: welcomeページにて存在しない案内（入部希望はコチラ）を HxS公式サイト（github.io）に変更
  resources/views/welcome.blade.php
Labels: Type: fix

#278 ポストデータを表示するコンポーネントを作成
  package-lock.json
  package.json
  resources/ts/src/components/Layouts/Dashboard.tsx
  resources/ts/src/features/posts/Posts.tsx
  resources/ts/src/features/posts/index.ts
Labels: Type: design

#279 fix: 適切なフィールド名に変更し，バリデーションルールが適応されるように変更
  app/Http/Requests/Posts/StoreRequest.php
Labels: Type: fix
